name: Bug Report
description: File a bug report.
title: "[🐞 Bug]: "
labels: ["bug", "triage"]
type: Bug

body:

  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**

  - type: checkboxes
    attributes:
      label: Is there an existing issue or a disscusion for this?
      description: Search for [existing issues](https://github.com/TorchMeter/torchmeter/issues?q=) or [existing discussions](https://github.com/TorchMeter/torchmeter/discussions?discussions_q=) for the bug you encountered.
      options:
        - label: I have searched, and found nothing match my bug.
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        What did you do, and what did you encounter?
        It is best to include a screenshot, gif or screen recording of your issue.
      placeholder: Tell us what did you do and what you see!
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: Expected result?
      description: Briefly describe your expected results.
      placeholder: Describe what you want!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Please describe exactly how to reproduce the bug.
      value: |
        <details>
        <summary>Steps</summary>

        1. 
        2. 
        3. 

        </details>
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Your package version
      description: Use `pip show torchmeter` to get the version.
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your os, like `windows 10`, `ubuntu 22.04`.
    validations:
      required: true

  - type: textarea
    id: appendix
    attributes:
      label: Appendix
      description: |
        Any addition information helping to resolve this issue is welcome.
        You can include code snippets, error traces, screenshots/GIFs, or other relevant materials here.
      value: |
        <details>
        <summary>Details</summary>

        1. 
        2. 
        3. 

        </details>
    validations:
      required: false
