# TorchMeter, MIT license
# Author: Ahzyuan
# Repo: https://github.com/Ahzyuan/torchmeter

name: 📤 Publish and Release 🗳

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  FORCE_COLOR: 1 

jobs:
    Build-distribution-packages:  
        name: 📦 Build distribution   
        runs-on: ubuntu-latest       

        steps: 
        - name: Fetch repository    
          uses: actions/checkout@v4 
        
        - name: Install Python       
          uses: actions/setup-python@v5 
          with:
              python-version: "3.x" 
        
        - name: Install dependencies  
          run: |   
              python3 -m pip install --upgrade pip
              python3 -m pip install setuptools build wheel isort ruff --user
              python3 -m pip install twine check-manifest --user
        
        - name: Build distribution packages  
          run: python3 -m build -v -n .
        
        - name: Execute validation script    
          run: |
            chmod +x ./check_meta.sh
            bash ./check_meta.sh

        - name: Store the building results   
          uses: actions/upload-artifact@v4
          with:
            name: build-results
            path: dist/
            if-no-files-found: error

    Publish-PyPI: 
        name: 📤 Publish to PyPI
        runs-on: ubuntu-latest
        
        needs: Build-distribution-packages 
      
        environment:
          name: pypi
          url: https://pypi.org/p/torchmeter  
          
        permissions:
          id-token: write  
      
        steps: 
        - name: Download all the dists
          uses: actions/download-artifact@v4
          with:
            name: build-results 
            path: dist/
        
        - name: Upload to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with: 
            skip-existing: true

    Publish-TestPyPI: 
      name: 📤 Publish to TestPyPI
      runs-on: ubuntu-latest

      needs: Build-distribution-packages 
  
      environment:
        name: testpypi
        url: https://test.pypi.org/p/torchmeter 
  
      permissions:
        id-token: write 
  
      steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: build-results 
          path: dist/

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

    Github-Release: 
        name: 🗳 Create a Release
        runs-on: ubuntu-latest

        needs: Build-distribution-packages

        permissions:
          contents: write 
  
        steps:              
        - name: Fetch repository
          uses: actions/checkout@v4
          
        - name: Generate Changelog 
          run: |
            awk -v RS="---" 'NR==1{gsub(/\n+$/, ""); print}' CHANGELOG.md > ${{ github.workspace }}-RELEASE.txt 
            cat ${{ github.workspace }}-RELEASE.txt
        
        - name: Download all the dists
          uses: actions/download-artifact@v4
          with:
            name: build-results
            path: dist/
        
        - name: Create GitHub Release
          env:
            GITHUB_TOKEN: ${{ github.token }}
          run: >-  
            gh release create
            '${{ github.ref_name }}'
            --repo '${{ github.repository }}'
            --notes "$(cat ${{ github.workspace }}-RELEASE.txt)"

        - name: Upload artifact to GitHub Release
          env:
            GITHUB_TOKEN: ${{ github.token }}
          run: >-
            gh release upload
            '${{ github.ref_name }}' dist/**
            --repo '${{ github.repository }}'
          
